main:
- identifier: startseite
  name: Startseite
  url: /
  weight: 1
- identifier: vision
  name: Vision
  url: /vision/
  weight: 2
- identifier: positionen
  name: Positionen
  url: /positionen/
  weight: 3
- identifier: algonews
  name: AlgoNews
  url: /algonews/
  weight: 4
- identifier: organisationen
  name: Organisationen
  url: /organisationen/
  weight: 5
- identifier: algoconsulting
  name: AlgoConsulting
  url: /algoconsulting/
  weight: 6
- identifier: fuehrung
  name: FÃ¼hrung
  url: /fuehrung/
  weight: 7
- identifier: die-allianz-in-bildern
  name: Die Allianz in Bildern
  url: https://docs.google.com/presentation/d/1Zq0WeUn4Z2uU2GjQDdeP-MXqAONxUg2u0tsfQaLP-p4/edit
  weight: 8
takePart:
- name: "Teilnehmen"
  url: "https://portal.algosphere.org/"
footer:
- identifier: rechtliche-hinweise
  name: Rechtliche Hinweise
  url: /rechtliche-hinweise/
  weight: 1
- identifier: cookies
  name: Cookies
  url: /#cookies
  weight: 2
